# Generated by Django 6.0.2 on 2026-03-02 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_hr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fullname',
            new_name='name',
        ),
    ]
