# Generated by Django 6.0.2 on 2026-03-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_student_is_verified_alter_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='resume',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='shortlisted',
            field=models.BooleanField(default=False),
        ),
    ]
