# Generated by Django 6.0.2 on 2026-03-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_student_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='hr_photos/'),
        ),
    ]
