# Generated by Django 6.0.2 on 2026-03-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_resume_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='match_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
