# Generated by Django 6.0.2 on 2026-03-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_jobapplication_match_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='projects',
            field=models.TextField(blank=True),
        ),
    ]
