# Generated by Django 6.0.2 on 2026-03-18 05:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_resume_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
