# Generated by Django 6.0.2 on 2026-03-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_resume_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
