# Generated by Django 6.0.2 on 2026-03-18 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_resume_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.hr'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
