# Generated by Django 6.0.2 on 2026-04-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_job_hr_jobapplication_status_alter_resume_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('student', 'Student'), ('hr', 'HR')], max_length=10)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
