# Generated by Django 6.0.2 on 2026-04-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='soft_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='projects',
            field=models.TextField(blank=True, null=True),
        ),
    ]
