# Generated by Django 6.0.2 on 2026-04-05 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_resume_soft_skills_alter_resume_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.hr'),
        ),
        migrations.AddField(
            model_name='message',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='interview_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
